INSERT INTO USERS (USER_ID,USER_LOGIN,USER_PASSWORD,USER_NOM,USER_PRENOM,USER_ROLE) values (null,'login1','password1','nom1','prenom1','ADMINISTRATEUR');
INSERT INTO USERS (USER_ID,USER_LOGIN,USER_PASSWORD,USER_NOM,USER_PRENOM,USER_ROLE) values (null,'login2','password2','nom1','prenom1','VISITEUR');

INSERT INTO COMPTES (COMPTE_ID,COMPTE_USER,COMPTE_LIBELLE) values (null,'user1','Livret A');
INSERT INTO COMPTES (COMPTE_ID,COMPTE_USER,COMPTE_LIBELLE) values (null,'user2','Livret Dev Durable');